LOG_PATH = "C:\\IMAGEM\\Eletrobras\\ONS_ELETROBRAS_BDIT\\log\\"

EXCEL_PATH = "C:\\IMAGEM\\Eletrobras\\ONS_ELETROBRAS_BDIT\\Planilha_entidades"
CSV_PATH = "C:\\IMAGEM\\Eletrobras\\ONS_ELETROBRAS_BDIT\\csv"
GDB_PATH = "C:\\IMAGEM\\Eletrobras\\ONS_ELETROBRAS_BDIT\\ModeloDadosBDIT.gdb"

LIST_GDB_LATLONG = ["TLT", "VLT"]

PORTAL_URL = 'https://geo2utilitiesap.img.com.br'
USERNAME = 'portaladmin'
PASSWORD = 'P4ssw0rd'
TYPESCRIPT_PATH = 'C:\\ArcGISExperienceBuilder\\client\\your-extensions\\widgets\\upload-excel\\src\\runtime\\widget.tsx'


DATADICTCSV_GDB_NAMES = {"BARRAMENTOS_BARRAMENTOS.csv": "BAR",
                         "BOBINA_BLOQUEIO_BOBINA_BLOQUEIO.csv": "BB",
                         "CAPACITOR_EM_DERIVACAO_CAPACITOR_EM_DERIVACAO.csv": "CAP",
                         "CAPACITOR_SERIE_FIXO_CAPACITOR_SERIE_FIXO.csv": "CSE",
                         "CAPACITOR_SERIE_TIRISTOR_CAPAC_SERIE_TIRISTOR.csv": "TCSC",
                         "CENTELHADOR_CENTELHADOR.csv": "CENTELHADOR",
                         "COMPENSADOR_ESTATICO_COMPENSADOR_ESTATICO.csv": "SVC",
                         "COMPENSADOR_SINCRONO_COMPENSADOR_SINCRONO.csv": "CSI",
                         "DECLARACAO_COMPROBATORIA_DECLARACAO_COMPROBATORIA.csv": "DECLARACAO_COMPROBATORIA",
                         "DISJUNTOR_DISJUNTOR.csv": "DJ",
                         "DISPOSITIVO_PROTECAO_Planilha1.csv": "PROTECAO_RELE",
                         "FILTRO_HARM_PASSIVO_FILTRO_HARM_PASSIVO.csv": "FILTRO",
                         "FILTRO_PLC_FILTRO_PLC.csv": "PLC",
                         "LINHAS TRANSMISSAO_LT_GERAL.csv": "LT_GERAL",
                         "LINHAS TRANSMISSAO_LT_GERAL_CABO_PARARAIO.csv": "LT_CABOS_PARARAIOS",
                         "LINHAS TRANSMISSAO_LT_PROJETO.csv": "LT_PROJETOS",
                         "LINHAS TRANSMISSAO_LT_PROJETO_CAPACIDADE_OPE.csv": "LT_PROJETOS_CAPACIDADESOPT",
                         "LINHAS TRANSMISSAO_LT_PROJETO_LTA.csv": "LT_PROJETO_LTA",
                         "LINHAS TRANSMISSAO_LT_PROJETO_LTA_SERIE_ESTR.csv": "LT_PROJETOS_SERIEESTRUTURAS",
                         "LINHAS TRANSMISSAO_LT_PROJETO_LTA_SISTEMA_AT.csv": "LT_PROJETOS_SISTEMAATERRAMENTO",
                         "LINHAS TRANSMISSAO_LT_PROJETO_LTS.csv": "LT_PROJETO_LTS",
                         "LINHAS TRANSMISSAO_LT_TRECHO.csv": "LT_TRECHOS",
                         "LINHAS TRANSMISSAO_LT_CRUZAMENTO.csv": "LT_CRUZAMENTO",
                         "LINHAS TRANSMISSAO_LT_OBSTACULO.csv": "LT_TRAVESSIAS_OBSTACULOS",
                         "LINHAS TRANSMISSAO_LT_PARALELISMO.csv": "LT_PARALELISMO",
                         "LINHAS TRANSMISSAO_LT_TORRE.csv": "TLT",
                         "LINHAS TRANSMISSAO_LT_VAO.csv": "VLT",
                         "LINHAS TRANSMISSAO_LT_VAO_CABO_PARARAIO.csv": "VLT_CABOS_PARARAIOS",
                         "LINHAS TRANSMISSAO_LT_PONTO_REF.csv": "TLT_PONTOREFERENCIA",
                         "PARA_RAIO_BCEXC_PARARAIOS.csv": "PR",
                         "REATORES_EM_DERIVACAO_REATOR_EM_DERIVACAO.csv": "RT",
                         "REATORES_LIMITADORCC_REATOR_LIMITADOR.csv": "RLICC",
                         "REATOR_ALISAMENTO_REATOR_ALISAMENTO.csv": "REATOR_DE_ALISAMENTO",
                         "REGISTRADOR_PERTURBACAO_REGISTRADOR_PERTURBACAO.csv": "REGISTRADOR_PERTURBACAO",
                         "SECCIONADOR_SECCIONADOR.csv": "SEC",
                         "TRANSFORMADOR_TRANSFORMADOR.csv": "TR",
                         "TRANSFORMADOR_CORRENTE_TC.csv": "TC",
                         "TRANSFORMADOR_POTENCIAL_TRANSFORMADOR_POTENCIAL.csv": "TP",
                         "VALVULA_VALVULA.csv": "VALVULAS",
                         "VALVULA_VAL_OBJETO_DESCRICAO.csv": "VALVULAS_DESCRICAO",
                         "VALVULA_VAL_OBJETO_TIRISTOR.csv": "VALVULAS_TIRISTOR",
                         "VALVULA_VAL_OBJETO_FAIXA_CORRENTE.csv": "VALVULAS_FAIXACORRENTE",
                         "VALVULA_VAL_OBJETO_FAIXA_TENSAO.csv": "VALVULAS_FAIXATENSAO",
                         "VALVULA_VAL_OBJETO_ANGULO_CONTROLE.csv": "VALVULAS_ANGULOSCONTROLE",
                         "VALVULA_VAL_REATANCIA_COMUTACAO.csv": "VALVULAS_REATANCIACOMUTACAO",
                         "VALVULA_VAL_OBJETO_CAPACITOR_COMUTACAO.csv": "VALVULAS_CAPACITORCOMUTACAO",
                         "VALVULA_VAL_NIVEIS_ISOLAMENTO.csv": "VAL_NIVEIS_ISOLAMENTO",
                         }

DATADICT_GDB_ALIAS = {'OBJECTID': 'OBJECTID',
                      'TX_NUM_EQUIPAMENTO': 'TX_NUM_EQUIPAMENTO',
                      'IdSubestacaoSiget': 'IdSubestacaoSiget',
                      'tiposBarramento': 'tiposBarramento',
                      'Documentos_Lista': 'Documentos_Lista',
                      'Anexo': 'Anexo',
                      'idCampo_item_da_lista_documentos': 'idCampo_item_da_lista_documentos',
                      'CODIGO_DECLARACAO': 'CODIGO_DECLARACAO',
                      'IdBDITDocumento_': 'IdBDITDocumento_',
                      'IdBDITDocumento_': 'IdBDITDocumento_',
                      'idDocumento_item_da_lista_documentos': 'idDocumento_item_da_lista_documentos',
                      'idBDITSubestacao': 'idBDITSubestacao',
                      'idBDITSubestacao2': 'idBDITSubestacao2',
                      'Tensao_Nominal_kV': 'Tensao_Nominal_kV',
                      'Tensao_Nominal_kV': 'Tensao_Nominal_kV',
                      'Nome_da_Linha': 'Nome_da_Linha',
                      'LOC_INSTALACAO_LT_GERAL': 'LOC_INSTALACAO_LT_GERAL',
                      'ID_CABO_PARARAIO': 'ID_CABO_PARARAIO',
                      'ANEXOS': 'ANEXOS',
                      'ID_PROJETO': 'ID_PROJETO',
                      'IdBDITProjetoLtGeral': 'IdBDITProjetoLtGeral',
                      'LOC_INSTALACAO': 'LOC_INSTALACAO',
                      'ID_CAPACIDADE_OPERATIVA': 'ID_CAPACIDADE_OPERATIVA',
                      'ID_PROJETO_LTA': 'ID_PROJETO_LTA',
                      'ID_SERIE_ESTRUTURA': 'ID_SERIE_ESTRUTURA',
                      'ID_SIST_ATERRAMENTO': 'ID_SIST_ATERRAMENTO',
                      'tipoContraPeso': 'tipoContraPeso',
                      'Caracteristicas_tecnicas_da_configuracao_de_aterramento_ANEXO': 'Caracteristicas_tecnicas_da_configuracao_de_aterramento_ANEXO',
                      'Caracteristicas_tecnicas_da_configuracao_de_aterramento_anexo': 'Caracteristicas_tecnicas_da_configuracao_de_aterramento_anexo',
                      'Desenho_das_torres_Anexo': 'Desenho_das_torres_Anexo',
                      'TRECHOS_DA_LT': 'TRECHOS_DA_LT',
                      'ID_OBSTACULO_LT': 'ID_OBSTACULO_LT',
                      'IdProjeto': 'IdProjeto',
                      'ID_PARALELISMO_LT': 'ID_PARALELISMO_LT',
                      'TipoCorrente': 'TipoCorrente',
                      'ID_PROJETO': 'ID_PROJETO',
                      'IDENT_TRECHO': 'IDENT_TRECHO',
                      'ID_SERIE_ESTRUTURA': 'ID_SERIE_ESTRUTURA',
                      'IdBDITTrechoLtGeral': 'IdBDITTrechoLtGeral',
                      'tipoEstruturaFinal': 'tipoEstruturaFinal',
                      'AutorizacaoLimpezaLtVao': 'AutorizacaoLimpezaLtVao',
                      'Codigo_Torre_1_Ponto_de_Referencia_1': 'Codigo_Torre_1_Ponto_de_Referencia_1',
                      'Codigo_Torre_2_Ponto_de_Referencia_2': 'Codigo_Torre_2_Ponto_de_Referencia_2',
                      'FUSO1': 'FUSO1',
                      'FUSO2': 'FUSO2',
                      'Anexo_1': 'Anexo_1',
                      'Anexo_2': 'Anexo_2',
                      'Anexo_3': 'Anexo_3',
                      'Anexo_01': 'Anexo_01',
                      'Anexo_02': 'Anexo_02',
                      'Documento_01': 'Documento_01',
                      'Documentos_01': 'Documentos_01',
                      'Documento_02': 'Documento_02',
                      'Documento_03': 'Documento_03',
                      'Documento_04': 'Documento_04',
                      'TensaoNominal_': 'TensaoNominal_',
                      'LOC_INSTALACAO_VAO': 'LOC_INSTALACAO_VAO',
                      'TensaoNominal': 'TensaoNominal',
                      'SUBESTACAO': 'SUBESTACAO',
                      'Fim_objeto_capacitorComutacao': 'Fim_objeto_capacitorComutacao'
                      }

DATADICT_CSV_GDB_NAMES = {'idNomeCabo_': 'idBDITNomeCabo',
                          'NumeroOperacional_': 'NumeroOperacional',
                          'Fabricante_': 'Fabricante',
                          'CapacidadeSobrecarga_': 'CapacidadeSobrecarga',
                          'CorrenteNominal_': 'CorrenteNominal',
                          'Frequencia_': 'Frequencia',
                          'NiveisIsolamentoAtmosferico_': 'NiveisIsolamentoAtmosferico',
                          'TensaoMaximaOperacaoContinua_': 'TensaoMaximaOperacaoContinua',
                          'conectividadeAtivo_': 'conectividadeAtivo',
                          'conectividadeAtivo2_': 'conectividadeAtivo2',
                          'TensaoNominalSistemaPontoInstalacao': 'TensaoNominalEquipamento',
                          'documentosArt': 'documentosART',
                          'idBditDocumentoArt': 'idBditDocumentoART',
                          'idTransmissoraSIGET_': 'idTransmissoraSIGET',
                          'DataInicioExecucaoLevantamento_': 'DataInicioExecucaoLevantamento',
                          'ObtencaoAltitudeNormal_': 'ObtencaoAltitudeNormal',
                          'DescricaoServicosExecutados_': 'DescricaoServicosExecutados',
                          'ResumoMonografiasVertices_':  'ResumoMonografiasVertices',
                          'IdLocalizacaoNomeEquipamento': "idBditLocalizacaoEquipamento",
                          'NumeroPatrimonio_': 'NumeroPatrimonio',
                          'descricaoDispositivo_': 'descricaoDispositivo',
                          'tipoRamalLinha_': 'tipoRamalLinha',
                          'idNomeCabo': 'IdBDITNomeCabo',
                          'Fator_de_carga_tipico': 'Fatordecargatipico',
                          'IndicetrechoLT': 'identificacaoTrechoLT',
                          'CodigoAtivoConcessionaria_': 'CodigoAtivoConcessionaria',
                          'CodigoPatrimonio': 'NumeroPatrimonio',
                          'ConectividadeAtivo2_': 'ConectividadeAtivo2',
                          'MRID_': 'MRID',
                          'IdAgenteProprietario_': 'IdAgenteProprietario',
                          'PotenciaNominal_': 'PotenciaNominal',
                          'TensaoNominal_': 'TensaoNominal',
                          'PossuiTCBucha_OpcaoTCBucha': 'OpcoesTCBucha',
                          '_DerivacaoEnrolamentosPrimarioDegrau': 'DerivacaoEnrolamentosPrimarioDegrau',
                          'derivacaoEnrolamentosSecundarioDegrau': 'DerivacaoEnrolamentosSecundarioDegrau',
                          'FatorSobretensaoTrintaSegundos_fatorSobretensaoDuranteSegundos': 'fatorSobretensaoDuranteSegundos',
                          'DataDesativacao_': 'DataDesativacao'

                          }
